#!/bin/bash

function download() {
    url=$1
    dest=$2

    response=$(curl -X GET ${url} -o -)
    format=$(echo ${response} | jq -r .format)
    if [ "${format}" = "base64" ] ; then
        echo ${response} | jq -j .content | base64 -d > $dest
    elif [ "${format}" = "text" ] ; then
        echo ${response} | jq -j .content > $dest
    else
        echo "Format ${format} of file ${dest} not supported"
        echo ${response} | jq -j .content > $dest
    fi
}

notebook_created="no"

function get_notebook() {
    ## Creates a new notebook if needed. Sets flag to delete if
    ## notebook was re-created.
    apiurl=$1
    sessionid=$2
    serviceid=$3
    svcinfo=`curl --silent -X GET "${apiurl}/${serviceid}" -H  "accept: application/json"`
    if [ $(echo ${svcinfo} | jq -j .sessionId) = "${sessionid}" ] ; then
        return ## NOTEBOOK_URL unchanged.
    fi
    
    svcinfo=`curl --silent -X POST "${apiurl}" -H  "accept: application/json" \
                  -H  "Content-Type: application/json" -d "{\"sessionId\":\"${sessionid}\"}"`
    notebook_created="yes"
    
    svcurl=`echo ${svcinfo} | jq -j .serviceURL`
    if [ "${svcurl}" = "null" ] ; then
        echo "Session ${sessionid} no longer exists. Cannot download data."
        exit 1
    fi

    SERVICE_ID=`echo ${svcinfo} | jq -j .id`
    echo "Wait for service ${SERVICE_ID} to be re-created at ${svcurl}."
    while ! curl --silent -IL -X GET ${svcurl} | grep "200 OK" ; do
        sleep 5
    done
    NOTEBOOK_URL=${svcurl}
}

function delete_notebook() {
    apiurl=$1
    if [ "${notebook_created}" = "yes" ] ; then
        curl -X DELETE "${apiurl}/${SERVICE_ID}" -H  "accept: */*"
    fi
}

function download_working_dir_data() {
    if [ ! -e download_filelist.dat ] ; then
        echo "Nothing to download from working dir."
        return
    fi
    apiurl=$1
    for file in `cat download_filelist.dat` ; do
        download ${apiurl}/${file} ${HOME}/${file}
    done
}

conda install -y -c conda-forge curl jq || exit 1


# =======================================================
# Everything below here is generated by the snapshot job:
# =======================================================
NOTEBOOK_URL=https://swirrl.climate4impact.eu/swirrl/jupyter/5eaf63e6-a0ce-433d-865c-fe29d220a860
SERVICE_ID=5eaf63e6-a0ce-433d-865c-fe29d220a860
get_notebook http://swirrl-api/swirrl-api/v1.0/notebook ce963e12-2242-473a-a047-826bf50bb4ac 5eaf63e6-a0ce-433d-865c-fe29d220a860
mkdir -p ~/data/staginghistory/stage.00002
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_222601-225012.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_222601-225012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp585_r1i1p3f1_gn_205101-207512.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp585_r1i1p3f1_gn_205101-207512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp585_r1i1p3f1_gn_207601-210012.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp585_r1i1p3f1_gn_207601-210012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_201501-202512.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_201501-202512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_202601-205012.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_202601-205012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/swirrl_fileinfo.json ~/data/staginghistory/stage.00002/swirrl_fileinfo.json
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_212601-215012.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_212601-215012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_227601-230012.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_227601-230012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_205101-207512.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_205101-207512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_210101-212512.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_210101-212512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_225101-227512.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_225101-227512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_207601-210012.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_207601-210012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_215101-217512.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_215101-217512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp585_r1i1p3f1_gn_202601-205012.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp585_r1i1p3f1_gn_202601-205012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp585_r1i1p3f1_gn_201501-202512.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp585_r1i1p3f1_gn_201501-202512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_220101-222512.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_220101-222512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_217601-220012.nc ~/data/staginghistory/stage.00002/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_217601-220012.nc
mkdir -p ~/data/staginghistory/stage.00001
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_222601-225012.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_222601-225012.nc
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_201501-202512.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_201501-202512.nc
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_202601-205012.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_202601-205012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/swirrl_fileinfo.json ~/data/staginghistory/stage.00001/swirrl_fileinfo.json
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_212601-215012.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_212601-215012.nc
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_227601-230012.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_227601-230012.nc
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_205101-207512.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_205101-207512.nc
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_210101-212512.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_210101-212512.nc
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_225101-227512.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_225101-227512.nc
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_207601-210012.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_207601-210012.nc
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_215101-217512.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_215101-217512.nc
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_220101-222512.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_220101-222512.nc
ln ~/data/staginghistory/stage.00002//tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_217601-220012.nc ~/data/staginghistory/stage.00001/tasmin_Amon_GISS-E2-2-G_ssp245_r1i1p3f1_gn_217601-220012.nc
ln -s ~/data/staginghistory/stage.00002 ~/data/latest
download_working_dir_data ${NOTEBOOK_URL}/api/contents
delete_notebook http://swirrl-api/swirrl-api/v1.0/notebook
